# These are supported funding model platforms

github: [YOUR_GITHUB_USERNAME]
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective name
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform name
custom: # Replace with your custom funding URL
